name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List files to verify Client folder exists
        run: ls -la

      - name: Zip Client folder contents
        run: |
          if [ -d "Client" ]; then
            cd Client
            zip -r ../entropymu_client.zip *
            cd ..
            echo "Zip file created successfully"
            ls -la entropymu_client.zip
          else
            echo "Client folder not found!"
            exit 1
          fi

      - name: Upload zip to release
        uses: softprops/action-gh-release@v1
        with:
          files: entropymu_client.zip
          token: ${{ secrets.GITHUB_TOKEN }}
